- name: Install nfs-kernel-server package
  apt:
    update_cache: true
    name: nfs-kernel-server

- name: Create exports' directories
  file:
    state: directory
    path: "{{ item.path }}"
  loop: "{{ nfs_server_exports }}"

- name: Template exports file
  template:
    src: exports.jinja2
    dest: "{{ nfs_server_exports_file_path }}"
  notify: reload nfs

- name: Make sure [nfsd] section exists in nfs.conf
  lineinfile:
    line: "[nfsd]"
    path: "{{ nfs_server_nfs_conf_file_path }}"
    create: yes
  notify: restart nfs

- name: Set nfsd bind address in nfs.conf
  lineinfile:
    insertafter: \[nfsd\]
    regexp: ^(?:#\s*)?host=.*
    line: "host={{ nfs_server_bind_address }}"
    path: "{{ nfs_server_nfs_conf_file_path }}"
  notify: restart nfs

- name: Start and enable nfs service
  service:
    name: "{{ nfs_server_service_name }}"
    state: started
    enabled: yes